Expose Tracer.copyTrace
palantir/tracing-java pull request #164
Opened 2019-05-29 19:56 UTC by yixunx

## Before this PR

There is no easy way to inspect the current trace without modifying the tracing state.

## After this PR

Exposed `Tracer.copyTrace` to allow access to the current tracing state.

2019-05-29 19:59 UTC, yixunx commented
The use case is documented in https://github.com/palantir/tracing-java/pull/163.

2019-05-30 16:10 UTC, iamdanfox requested changes
I think this is dangerous

2019-05-30 18:23 UTC, yixunx commented
@iamdanfox Can you give an example for why this is dangerous? I think it's fine if we only return a deep copy, but I might be missing some context here.

2019-06-06 14:22 UTC, ferozco commented
@iamdanfox what is your concern?

2019-06-10 15:17 UTC, yixunx commented
@iamdanfox 	Actually I just found out that there is already a `Tracer.isTraceObservable()` that does what we need, so we don't need this PR to support the use case mentioned #163. I do have another potential use case for exposing part of the current trace info, but I'll open a separate PR to discuss.

2019-06-10 15:17 UTC, closed without merging